### ISSUE TITLE
support addContext inside before and after hooks

### ISSUE THREAD

**Issue by jsnwu** [adamgruber/mochawesome#165]
AddContext can be used in beforeEach and AfterEach https://github.com/adamgruber/mochawesome/commit/c96e4adf7651bfbc3604b0200b81026687f4a2ea. It will be great to support before and after hooks so that information that's related to the whole test suite can be added to the section near the suite title.

**Comment by adamgruber** [comment]
`addContext` will work inside `before` and `after` hooks. However, I think there is a bug in displaying these hooks if they exist inside a suite without adjacent test cases.

This works:
```js
describe('Context', () => {
  before(function () {
    addContext(this, 'some context');
  });

  it('tests something', () => {
    //...
  });
});
```

This doesn't work:
```js
describe('Context', () => {
  before(function () {
    addContext(this, 'some context');
  });

  describe('Tests In Here', () => {
    it('tests something', () => {
      //...
    });
  });
});
```

I'll need to look into it further to determine the fix.

**Comment by jsnwu** [comment]
Looks like the before hook works. It attaches the info to the adjacent test case. The after hook doesn't work for me. 

I am using the reporter with NighwatchJs, so there's a browser variable
```
before(function (browser, done) {
    addContext(this, json);
    done();
});

after(function (browser, done) {
    addContext(this, json);
    done();
})

it('abcd', function(browser){
    browser.pause(100);
});
```

It will be great to have a dedicated section in the report to show the info attached in the before and after hooks.

**Comment by adamgruber** [comment]
Using code similar to what you have, it works as expected in my testing.

Here's my code:

```js
describe('Testing Before/After', () => {
  before('before', function () {
    addContext(this, 'context before all');
  });

  after('after', function () {
    addContext(this, 'context after all');
  });

  it('adds 1 plus 1', function () {
    (1+1).should.equal(2);
    addContext(this, 'context');
  });
});
```

And this is the report:

![screen shot 2017-06-26 at 1 56 15 pm](https://user-images.githubusercontent.com/2378900/27553014-67ead78e-5a77-11e7-8774-fc2f2d73caf6.png)


You do need to make sure you have enabled hooks in the settings in order to see them in the report. By default, hooks only show if they failed. This is purposeful as to not clutter up the report.

![screen shot 2017-06-26 at 1 58 22 pm](https://user-images.githubusercontent.com/2378900/27553069-919716ba-5a77-11e7-8df2-1d64e97e7868.png)

**Comment by jsnwu** [comment]
Ok. I can see the after hook after enabling it on the side bar.

**Comment by jsnwu** [comment]
I am keeping only 1 report file each time. The report setting will be overwritten after new one is generated. So the show hook flag always reset to the default hidden setting. Is it possible to add a config or global env to enable/override the hooks display by default value?

**Comment by adamgruber** [comment]
Yeah I can see how that's kind of a pain. I'll consider adding an option.

**Comment by adamgruber** [comment]
@jsnwu I just released v2.3.0 with a new option, `showHooks`.

**Comment by superhero** [comment]
Shouldn't this issue be reopened? Or is there a different issue regarding the issue described by @adamgruber :

> This doesn't work:

```
describe('Context', () => {
  before(function () {
    addContext(this, 'some context');
  });

  describe('Tests In Here', () => {
    it('tests something', () => {
      //...
    });
  });
});
```
I currently use nested describe, and it seems to be a persisted problem still.

**Comment by superhero** [comment]
Actually, as you can see here, it's even stranger then that. it worked the last time, but not the first two times.

![screenshot from 2018-05-03 13-48-49](https://user-images.githubusercontent.com/839818/39574869-deed7854-4ed8-11e8-914b-159431f1a8fe.png)

**Comment by adamgruber** [comment]
The image above shows that context was added to both the `flattenRoutes` and `findRoute` tests as indicated by the speech bubble icon.

Could you try adding a description to your `before` function call?
```js
before('before', function() {
  addContext(this, { title:'config', value:config });
}
```

**Comment by superhero** [comment]
This problem was local, still strange though... I changed a different test in a different file, and it solved this problem as well. No idea what happened... just moved some code into a before callback.

**Comment by superhero** [comment]
You can kinda see here that the `controller/server/http/router` description also is wrapped, but it's really not. After I moved the code around in the other test file, it now also renders correctly, as a top level `describe`
